name: Build xdg-desktop-portal-luminous (archlinux)

on: [push, pull_request]
jobs:
  build:
    name: "Build xdg-desktop-portal-luminous"
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
       - uses: actions/checkout@v6
       - name: "install deps"
         run: |
           pacman -Syu --noconfirm base-devel clang meson ninja pipewire libxkbcommon wayland cairo pango egl-wayland
       - uses: dtolnay/rust-toolchain@stable
         with:
           components: clippy rustfmt
       - name: Run fmt check
         run: cargo fmt --all -- --check
       - name: Run clippy
         run: cargo clippy -- -D warnings
       - name: build target
         run: |
           meson setup build
           meson compile -C build


  github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to create release
      id-token: write # required for OIDC token exchange
    needs: build
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: taiki-e/create-gh-release-action@56a8b3f8449593aa02b91f7b84da564f476e94f0 # v1.9.2
        with:
          branch: master
          changelog: CHANGELOG.md
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish github release
        run: |
          if [[ $(echo "${GTIHUB_REF#refs/tags/v}" | grep '-' > /dev/null) ]]; then
            gh release edit "${GITHUB_REF#refs/tags/}" --prerelease
          fi
          gh release edit "${GITHUB_REF#refs/tags/}" --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
